// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!

using System.Runtime.InteropServices;

namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

public static class ExportsInterop {

    public static IExports Exports {get; set;}

    [UnmanagedCallersOnly(EntryPoint = "foo:foo/floats#float32-param")]
    public static void wasmExportFloat32Param(float p0) {
        Exports.Float32Param(p0);
        
    }
    [UnmanagedCallersOnly(EntryPoint = "foo:foo/floats#float64-param")]
    internal static void wasmExportFloat64Param(double p0) {
        Exports.Float64Param(p0);
        
    }
    [UnmanagedCallersOnly(EntryPoint = "foo:foo/floats#float32-result")]
    internal static float wasmExportFloat32Result()
    {
        return Exports.Float32Result();
        
    }
    [UnmanagedCallersOnly(EntryPoint = "foo:foo/floats#float64-result")]
    internal static double wasmExportFloat64Result()
    {
        return Exports.Float64Result();
        
    }
    
}

