// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

public interface IExports {
    void Float32Param(float p0);
    void Float64Param(double p0);
    float Float32Result();
    double Float64Result();
}

