// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

public static class ExportsInterop {

    public static IExports Exports {get; set;}
    
    internal static void wasmExportFloat32Param(float p0) {
        Exports.Float32Param(p0);
        
    }
    internal static void wasmExportFloat64Param(double p0) {
        Exports.Float64Param(p0);
        
    }
    internal static float wasmExportFloat32Result() {
        return Exports.Float32Result();
        
    }
    internal static double wasmExportFloat64Result() {
        return Exports.Float64Result();
        
    }
    
}

