// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;


public static class Imports {
    
    public static void float32Param(float x) {
        ImportsInterop.wasmImportFloat32Param(x);
        
    }
    public static void float64Param(double x) {
        ImportsInterop.wasmImportFloat64Param(x);
        
    }
    public static float float32Result() {
        var result =  ImportsInterop.wasmImportFloat32Result();
        return result;
        
    }
    public static double float64Result() {
        var result =  ImportsInterop.wasmImportFloat64Result();
        return result;
        
    }
}

