// Generated by `wit-bindgen` 0.6.0. DO NOT EDIT!
#include "the_world.h"


__attribute__((__import_module__("imports"), __import_name__("float32-param")))
void __wasm_import_imports_float32_param(float);

__attribute__((__import_module__("imports"), __import_name__("float64-param")))
void __wasm_import_imports_float64_param(double);

__attribute__((__import_module__("imports"), __import_name__("float32-result")))
float __wasm_import_imports_float32_result(void);

__attribute__((__import_module__("imports"), __import_name__("float64-result")))
double __wasm_import_imports_float64_result(void);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

void imports_float32_param(float x) {
  __wasm_import_imports_float32_param(x);
}

void imports_float64_param(double x) {
  __wasm_import_imports_float64_param(x);
}

float imports_float32_result(void) {
  float ret = __wasm_import_imports_float32_result();
  return ret;
}

double imports_float64_result(void) {
  double ret = __wasm_import_imports_float64_result();
  return ret;
}

__attribute__((__export_name__("exports#float32-param")))
void __wasm_export_exports_float32_param(float arg) {
  exports_float32_param(arg);
}

__attribute__((__export_name__("exports#float64-param")))
void __wasm_export_exports_float64_param(double arg) {
  exports_float64_param(arg);
}

__attribute__((__export_name__("exports#float32-result")))
float __wasm_export_exports_float32_result(void) {
  float ret = exports_float32_result();
  return ret;
}

__attribute__((__export_name__("exports#float64-result")))
double __wasm_export_exports_float64_result(void) {
  double ret = exports_float64_result();
  return ret;
}

extern void __component_type_object_force_link_the_world(void);
void __component_type_object_force_link_the_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_the_world();
}

// Generated by `wit-bindgen-csharp` 0.1.0. DO NOT EDIT!
#include <stdlib.h>

#include <mono-wasi/driver.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/class.h>
#include <mono/metadata/appdomain.h>
#include <mono/metadata/image.h>
#include <mono/metadata/metadata.h>
#include <mono/metadata/object.h>
#include <mono/metadata/debug-helpers.h>
#include <mono/metadata/reflection.h>
#include <mono/utils/mono-publib.h>

#define DEFINE_DOTNET_METHOD(c_name, assembly_name, namespc, class_name, method_name) MonoMethod* method_##c_name;__attribute__((export_name(c_name)))MonoObject* c_name(MonoObject* target_instance, void* method_params[]) {if (!method_##c_name) {method_##c_name = lookup_dotnet_method(assembly_name, namespc, class_name, method_name, -1);assert(method_##c_name);}MonoObject* exception;MonoObject* res = mono_wasm_invoke_method(method_##c_name, target_instance, method_params, &exception);assert(!exception);return res;}

DEFINE_DOTNET_METHOD(exports_float32_param, "exportsFloat32Param.dll", "exports_float32_param.Wit.Native" , "Interop", "wasmExportFloat32Param");
DEFINE_DOTNET_METHOD(exports_float64_param, "exportsFloat64Param.dll", "exports_float64_param.Wit.Native" , "Interop", "wasmExportFloat64Param");
DEFINE_DOTNET_METHOD(exports_float32_result, "exportsFloat32Result.dll", "exports_float32_result.Wit.Native" , "Interop", "wasmExportFloat32Result");
DEFINE_DOTNET_METHOD(exports_float64_result, "exportsFloat64Result.dll", "exports_float64_result.Wit.Native" , "Interop", "wasmExportFloat64Result");

void attach_internal_calls() {
    mono_add_internal_call("Wit.Native.ImportsInterop::wasmImportFloat32Param", imports_float32_param);
    mono_add_internal_call("Wit.Native.ImportsInterop::wasmImportFloat64Param", imports_float64_param);
    mono_add_internal_call("Wit.Native.ImportsInterop::wasmImportFloat32Result", imports_float32_result);
    mono_add_internal_call("Wit.Native.ImportsInterop::wasmImportFloat64Result", imports_float64_result);
}

