// Generated by `wit-bindgen` 0.6.0. DO NOT EDIT!
#ifndef __BINDINGS_THE_WORLD_H
#define __BINDINGS_THE_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Imported Functions from `imports`
void imports_float32_param(float x);
void imports_float64_param(double x);
float imports_float32_result(void);
double imports_float64_result(void);

// Exported Functions from `exports`
void exports_float32_param(float x);
void exports_float64_param(double x);
float exports_float32_result(void);
double exports_float64_result(void);

#ifdef __cplusplus
}
#endif
#endif
